### ISSUE TITLE
Should we remove all namespaces in ekat, except ekat itself?

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/EKAT#10]
The ekat namespace should already be enough to encapsulate ekat's stuff in any downstream application. Is there really a point in having, say, `ekat::util`? After all, isn't everything in ekat a utility function/class anyways? Also  the `ekat::pack` namespace seems to be an overkill.

The reason why I would purge nested namespaces like `util` is that it would somewhat help keeping downstream codes shorter. Sure, one can always issue a `using ekat::util::blah`/`using blah = ekat::util::blah`, or even `using namespace ekat::util', but it all seems overly complicated.

Note: any sort of `impl` or `details` namespace should be kept, since they have a completely different purpose (isolating stuff that the user should not try to use/access).

**Comment by jgfouca** [comment]
I'd be fine with that.

**Comment by bartgol** [comment]
@jeff-cohere , what's your take?

**Comment by jeff-cohere** [comment]
I like this idea. The fewer things someone has to learn to use EKAT, the better.

**Comment by jeff-cohere** [comment]
I'll do this after #19.

**Comment by jeff-cohere** [comment]
There's an issue with this: there are `min` and `max` functions defined both in the `ekat::util` namespace and in the `ekat::pack` namespace. The ones in `ekat::util` provide surrogates for missing GPU functions, and the latter work on Packs. So if we flatten the `util` and `pack` namespace to just `ekat`, we get a name collision.

Thoughts on how to resolve this? Should we be more specific about the kinds of arguments that can be accepted in our `min` and `max` functions?

**Comment by bartgol** [comment]
Ugh, that's a pain. Using some SFINAE could help to restrict the usage of each function. However, lines like 
```
ekat_pack_gen_bin_fn_all(min, util::min)
```
will likely cause infinite recursion if the second input didn't have a scope resolution.

I think there are two solutions:
1) keep the util namespace for some _limited_ things, like this one;
2) rename `util::min/max` to something like `device_min, device_max`.

I'm not a fan of either approach.

Perhaps a third one: the math utils in `ekat_math_utils.hpp` are, as the comment says, drop in replacements for std functions that don't run on GPU. Maybe such utilities deserve a more specific namespace than 'util' (quite vague). Maybe something like `std_device_utils`, or something along that line?

**Comment by jeff-cohere** [comment]
What about `ekat::math`?

**Comment by bartgol** [comment]
Well, wouldn't one think that a pow function for packs should fall in that namespace as well, being a math function?

**Comment by jeff-cohere** [comment]
Yeah, I thought of that right after I hit the comment button. :-/ If we limit the contents of this additional namespace to functions that fill gaps on GPUs, maybe it should be something like `std_device_utils`. Kind of a mouthful, though, that. Is `std_device` too unclear?

**Comment by bartgol** [comment]
Maybe we could simply keep those functions for ourselves, and put them in a `details` or `impl` namespace. The user can still grab them if need be, but it's not that likely.

I grepped for `isfinite` and `max_element` in both ekat and scream, and didn't find anything (except that their definition in ekat). And the min/max functions are _so tiny_ that one probably doesn't even need to use ekat's version, and can simply do the `?:` op on the fly...

**Comment by jeff-cohere** [comment]
I like the idea of tucking them into an `impl` namespace. Then, if people clamor for them, we can discuss where they belong.
