### ISSUE TITLE
Add Pack::set(mask, const Pack pack_true, const Pack pack_false) function.

### ISSUE THREAD

**Issue by overfelt** [E3SM-Project/EKAT#100]
I would like to have an if/then/else type set in order to replace
  A.set(mask, B);
  A.set(!mask, C); 
with
  A.set(mask,B,C);
From what I have have read in SIMD tutorials, this would directly translate into a SIMD call that is widely available and could default to the two assignment operators if not.

**Comment by bartgol** [comment]
@overfelt I suggested precisely this when I was reviewing a PR in scream. It would be much better than doing

```
A = B;
A.set(mask,C);
```
which is much harder to read.

I can get on this today.

**Comment by overfelt** [comment]
Thanks.
