### ISSUE TITLE
Add scalar-only overloads for `ekat::max`, `ekat::min`, `ekat::abs`

### ISSUE THREAD

**Issue by jeff-cohere** [E3SM-Project/EKAT#169]
**Is your feature request related to a problem? Please describe.**
One of the nice things about EKAT is that it provides functions that should work for both packs and scalar types. Interestingly, the `min`, `max`, and `abs` functions offered don't seem to include cases for pairs of scalar arguments. Let's add these!

**Comment by bartgol** [comment]
If you issue, say, `using std::min` in your app code, then I believe that `min(a,b)` should work, no?

**Comment by jeff-cohere** [comment]
The ones in `ekat_math_utils.hpp` seem to be under the `ekat::impl` namespace, which suggests "no touchy!".

**Comment by bartgol** [comment]
Ah, yeah, you're right. I guess we put them there to not explicitly pollute ekat's namespace, in case the user does `using namespace ekat`, but doesn't want these overloads.

**Comment by jeff-cohere** [comment]
It seems like a user who includes that header might not mind having those functions available in the `ekat` namespace. Otherwise they get only the`is_invalid` and `transpose` functions.

**Comment by bartgol** [comment]
I think that names like max or min are so common that it would be somewhat dangerous to inject them into ekat's namespace. I can see apps doing `using namespace ekat`, but if they also are doing (ugh) `using namespace std` (or any other library namespace that declares max/min), then there might be compile/link errors (or worse, runtime ones).

I'm ok moving unambiguous names outside of the impl namespace, but max/min (and even isfinite) are shared with the std lib, which imho is too dangerous to do it by default. If someone is interested in getting those functions, they can do `using namespace ekat::impl`. It's a one line price to pay, but it gives more security long term.

**Comment by jeff-cohere** [comment]
Okay, that's a fair point. I don't particularly sympathize with anyone who gets all sorts of errors when they use `using namespace std`, but we probably don't want to contribute any more to the confusion.

**Comment by bartgol** [comment]
I agree, using the std namespace is not a great practice. But on the other hand, there are likely other libs that may overload such common name functions...
