### ISSUE TITLE
Get a Mac build working

### ISSUE THREAD

**Issue by pbosler** [E3SM-Project/EKAT#18]
EKAT fails to build on mac; gcc has a few non-std goodies that aren't in the mac os.

With this issue, we identify and collect the barriers to an ekat/mac build, and their solutions.

Alternatives: Don't use mac.  This was easier pre-covid.  With virtual work and vpn hassles, it would be great to have a laptop build.

**Comment by pbosler** [comment]
**Floating point exception handling.**   Gnu has non-standard functions, e.g., `feenableexcept` that help with floating point exceptions; these aren't included in the Mac OS native compilers.

This CMake block identifies the problem (tested on both linux and mac --- the `#cmakedefine` works properly):
```
include(CheckSymbolExists)
check_symbol_exists(feenableexcept "fenv.h" HAVE_FEENABLEEXCEPT)
if (NOT HAVE_FEENABLEEXCEPT)
  option(EKAT_NEEDS_FEENABLEEXCEPT "compiler does not include feenableexcept." ON)
endif()
```

And adding these functions if the above check is true, fixes this:

```
static int
fegetexcept (void)
{
  static fenv_t fenv;

  return fegetenv (&fenv) ? -1 : (fenv.__control & FE_ALL_EXCEPT);
}

static int
feenableexcept (unsigned int excepts)
{
  static fenv_t fenv;
  unsigned int new_excepts = excepts & FE_ALL_EXCEPT,
               old_excepts;  // previous masks

  if ( fegetenv (&fenv) ) return -1;
  old_excepts = fenv.__control & FE_ALL_EXCEPT;

  // unmask
  fenv.__control &= ~new_excepts;
  fenv.__mxcsr   &= ~(new_excepts << 7);

  return ( fesetenv (&fenv) ? -1 : old_excepts );
}

static int
fedisableexcept (unsigned int excepts)
{
  static fenv_t fenv;
  unsigned int new_excepts = excepts & FE_ALL_EXCEPT,
               old_excepts;  // all previous masks

  if ( fegetenv (&fenv) ) return -1;
  old_excepts = fenv.__control & FE_ALL_EXCEPT;

  // mask
  fenv.__control |= new_excepts;
  fenv.__mxcsr   |= new_excepts << 7;

  return ( fesetenv (&fenv) ? -1 : old_excepts );
}
```

Note: This issue is summarized well [here](https://philbull.wordpress.com/2012/12/09/update-floating-point-exception-handling-on-mac-os-x/).  
And a solution dating back to 2009 can be found [here, fe-handling-example.c](http://www-personal.umich.edu/~williams/archive/computation/fe-handling-example.c)

The solution posted above takes only a snippet of code from `fe-handling-example.c`, which lists a Public Domain license.  The whole code contains special cases for older Mac architectures (e.g., PPC) that we likely won't need.

**Comment by pbosler** [comment]
### Packs and pow

To get `ekat_pack.hpp` various impls of `pow` to work, I had to remove the explicit template parameter for `std::pow`, e.g.,

- Before: `s[i] = std::pow<typename PackType::scalar>(a[i], b);`
- After:    `s[I] = std::pow(a[I],b)`

**Explanation & details:**

In the Apple version of `math.h` is the following impl of `std::pow`:

```
template <class _A1, class _A2>
inline _LIBCPP_INLINE_VISIBILITY
typename std::__lazy_enable_if
<
    std::is_arithmetic<_A1>::value &&
    std::is_arithmetic<_A2>::value,
    std::__promote<_A1, _A2>
>::type
pow(_A1 __lcpp_x, _A2 __lcpp_y) _NOEXCEPT
{
    typedef typename std::__promote<_A1, _A2>::type __result_type;
    static_assert((!(std::is_same<_A1, __result_type>::value &&
                     std::is_same<_A2, __result_type>::value)), "");
    return ::pow((__result_type)__lcpp_x, (__result_type)__lcpp_y);
}
```

The "before" lines above from `ekat_pack.hpp` failed the static_assert.  

Warning for @pbosler and @jeff-cohere : This change has not yet been tested on linux.

**Comment by pbosler** [comment]
### constexpr and `ekat::util::ScalingFactor`

The `constexpr` constructor of `ScalingFactor` uses `std::get<>`, which is apparently not a `constexpr`.  Clang doesn't like this.

```
/Users/pabosle/ekat/src/ekat/util/ekat_scaling_factor.hpp:25:13: error: constexpr constructor never produces a
      constant expression [-Winvalid-constexpr]
  constexpr ScalingFactor (const RationalConstant& b,
            ^
/Users/pabosle/ekat/src/ekat/util/ekat_scaling_factor.hpp:27:11: note: non-constexpr function 'get<0,
      ekat::util::RationalConstant, 2>' cannot be used in a constant expression
   : base(std::get<0>(check_and_adjust(b,e)))
```

**Comment by bartgol** [comment]
This is linked to E3SM-Project/scream#484. In fact, we were ddiscussing a similar solution regarding FPE on Mac OS.

**Comment by bartgol** [comment]
> ### constexpr and `ekat::util::ScalingFactor`
> 
> The `constexpr` constructor of `ScalingFactor` uses `std::get<>`, which is not a `constexpr`. Clang doesn't like this.
> 
> **Note:** In c++14, `std::get` is `constexpr`. Easy fix: configure with `-DCMAKE_CXX_STANDARD=14`

We need to be more strict in our testing, and ensure that C++11 only features are allowed (no free C++14 ones). I thought that was already the case, but I guess gcc is one step ahead, and introduced some C++14 feature earlier.

I'm somewhat reluctant to require C++14. Don't get me wrong, I'd love C++14, actually I'd like C++17 and sometimes even C++20 (templated lambda, concept...). The reason I'm reluctant is the support we can expect on our target machines. IIRC, on Summit we can only rely on C++11. I'm not sure if we can count on C++14, definitely not on C++17 (cuda's not there yet, at least not with stable versions).

Some files in Ekat are precisely trying to backport some of the C++14 features (and kokkos also does that, sometimes). However, some things cannot be backported, like whether or not a function is marked constexpr in std namespace. =(

I'm not sure what the best course of action is here. Supporting Mac builds is nice, but there are no "production" mac machines, which makes me somewhat reluctant to hack our codes (sometimes removing features) just for convenience of developing on Mac. That said, a constexpr constructor for ScalingFactor is probably not necessary (I don't foresee anyone using compile-time ScalingFactor instances...), so maybe we could simply remove the constexpr keyword in these cases...

**Comment by pbosler** [comment]
I just checked linux, with gcc7.3 and -DCMAKE_CXX_STANDARD=11, and everything builds and all tests pass.   And since, as you say, there are no HPC Mac machines, so I don't think we need to require c++14 for ekat at all --- just leave it as a note, "If you want to build on Mac, you'll need to set this cmake variable."

**Comment by jeff-cohere** [comment]
I think the fact that we build/test on a variety of non-Mac machines will likely keep us honest. But let's keep our eyes open for better workarounds.

**Comment by bartgol** [comment]
@pbosler The CMake solution for special-handling of Mac OS seems reasonable.

**Comment by pbosler** [comment]
Cool.  I put it in #21 later this morning.
