### ISSUE TITLE
TPL Catch2 is incomplete

### ISSUE THREAD

**Issue by abagusetty** [E3SM-Project/EKAT#211]
`Catch2` is not being cloned in recursive case. 

Looks like an incomplete clone: https://github.com/E3SM-Project/EKAT/blob/master/.gitmodules#L12
Is it missing `.git` ?

**Comment by bartgol** [comment]
Uhm, it seems to work for me:

```
$ git clone --recursive git@github.com:E3SM-Project/EKAT.git 
...
$ cd EKAT
$ ls extern/Catch2
appveyor.yml  BUILD.bazel  CMakeLists.txt  CODE_OF_CONDUCT.md  contrib  examples  LICENSE.txt  projects   scripts         src          WORKSPACE
artwork       CMake        codecov.yml     conanfile.py        docs     include   misc         README.md  single_include  third_party
```

**Comment by abagusetty** [comment]
Sorry @bartgol about an incomplete description. I believe the directory of Catch2 under extern was observed to be empty ? Also I get to see compilation errors from missing `"catch2/catch.hpp"` because of the above missing `.git` in submodules. Can you please verify the above claim

**Comment by bartgol** [comment]
My Catch2 folder is not empty. The `.git` at the end usually indicates a bare repository. In the case of github, I think it's irrelevant.

Did all the other tpls clone correctly?

**Comment by abagusetty** [comment]
Yes, all other 3 were cloned properly except Catch2.

**Comment by bartgol** [comment]
Are you able to manually clone Catch2 using the same url listed in `.gitmodules`?

**Comment by abagusetty** [comment]
I can get back on re-verifying the issue. This can very well be a false alarm, for that I can close this issue. I had other edits for HIP, SYCL that might have messed up.

**Comment by abagusetty** [comment]
Apologies, turned out to be a false alarm. Closing it.
