### ISSUE TITLE
EKAT valid_nested_list_format uses size_t for an integer, num_open, that might go negative

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/EKAT#226]
Associated warning:
```
ekat/src/ekat/util/ekat_string_utils.cpp(179): warning: pointless comparison of unsigned integer with zero
```

**Comment by bartgol** [comment]
Thanks! I forgot to add `-Wextra` to my ekat debug build, and this slipped through the cracks. Will fix.

Side node: imho, such pointless comparisons are potentially dangerous (flawed logic), and gcc should include the warning in `-Wall`, rather than `-Wextra`.
