### ISSUE TITLE
Append to rather than set CXXFLAGS, etc.

### ISSUE THREAD

**Issue by ambrad** [E3SM-Project/EKAT#242]
Here: https://github.com/E3SM-Project/EKAT/blob/34d2130791dbe116a43bfcf1afaa605b74c9f114/cmake/EkatSetCompilerFlags.cmake#L127-L133 CXXFLAGS is being set rather than string-appended to. This overwrites flags from E3SM's cime_config cmake files.

**Comment by ambrad** [comment]
Lines of this sort: https://github.com/E3SM-Project/EKAT/blob/34d2130791dbe116a43bfcf1afaa605b74c9f114/cmake/EkatSetCompilerFlags.cmake#L36 are also a problem.

**Comment by ambrad** [comment]
Never mind; this can't be it. CXXFLAGS is empty on entry to ekat/CMakeLists.txt.

**Comment by bartgol** [comment]
I think this might be an issue. Macros do not create new scopes, so using a very common name like CXXFLAGS in that macro will alter the value of a potential homonymous var at the call site.

**Comment by bartgol** [comment]
I confirmed that this _is_ an issue. I put

```
set (CXXFLAGS "hello world")
```
at the top of scream's CMakeLists.txt, and printed its value at the bottom, where it showed `-Wall` instead of `hello world`. I will fix this right away.
