### ISSUE TITLE
Add a `sum` function to `ekat_pack.hpp`.

### ISSUE THREAD

**Issue by jeff-cohere** [E3SM-Project/EKAT#26]
**Is your feature request related to a problem? Please describe.**
See [Andrew Bradley's comment in SCREAM PR 536](https://github.com/E3SM-Project/scream/pull/536/files#r480314177). It would be helpful to have a `sum` function that returns the sum of all elements in a pack.

**Describe the solution you'd like**
The proposed solution is to define the following inline function in `ekat_pack.hpp`:

```
template <typename PackType> KOKKOS_INLINE_FUNCTION
OnlyPackReturn<PackType, typename PackType::scalar> reduce_sum (const PackType& p) {
  typename PackType::scalar v(p[0]);
  vector_simd for (int i = 1; i < PackType::n; ++i) v += p[i];
  return v;
}
```

**Additional context**

**Comment by bartgol** [comment]
For similarity with Intel's AVX512 instruction, I would call it `reduce_add`, or maybe `reduce_sum`; having `reduce` in the name makes it clear it is summing _within_ the vector (and it's also easier to grep). But that's just a personal preference.

**Comment by bartgol** [comment]
Also, is there really any benefit in decorating the loop with simd? I know someone might say "worst case scenario, nothing happened, so you get the same behavior as without the `vector_simd` macro", but I'm always wary of adding things "just in case", when they could be misleading...

**Comment by jeff-cohere** [comment]
> For similarity with Intel's AVX512 instruction, I would call it `reduce_add`, or maybe `reduce_sum`; having `reduce` in the name makes it clear it is summing _within_ the vector (and it's also easier to grep). But that's just a personal preference.

I think that's fine. Wouldn't this also be the case for `min` and `max`, too? Can you point me to a link that describes the AVX-512 instruction you're referring to?

Regarding `vector_simd`: I had no specific reason for including it. I just copy-pasted the `min` (or `max`) implementation. I'm not versed in all of this machinery just yet.

**Comment by bartgol** [comment]
[This](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#) is the intel intrinsics guide, which includes plenty of vector extension versions. Probably you're most interested in AVX2 and AVX512 (the latter comes in n+1 flavors).

I don't think using similar names to avx is stricly necessary, but it might help convey the message that packs are to enhance vectorization (in case it wasn't already clear).

BTW, in this case, without using intrinsics, I'm not sure if the compiler is smart enough to use vector instructions to achieve better-than-scalar performance. Probably not. One would have to manually implement a divide-and-conquer strategy (like sum(pack) = sum(pack[0:N/2)+pack[N/2,N)). However, I don't know if this is worth the effort. I think one would have to do _many_ reduction ops for its cost to become noticeable compared to the rest.

**Comment by jeff-cohere** [comment]
Thanks for the link! I've updated the proposed solution above.

**Comment by ambrad** [comment]
You need `vector_simd` (which maps to `#pragma omp simd`; see docs for that to understand the motivation) in there. All pack routines _must_ include it. We're telling the compiler with maximum intensity that it must vectorize the loop.

**Comment by bartgol** [comment]
I was just wondering whether the simd pragma does anything here, since the different iterations all update the same quantity. In this scenario, it seems to me that the correct pragma would be `#pragma omp simd reduction(+:output_var_name)`. I wonder if a simple  omp simd does anything at all here (or whether it does the right thing). There is not much online for data races on the output variable in simd operations. And all the reduction examples add the `reduction(+:var)` clause.

**Comment by ambrad** [comment]
Good point. Actually, for min, max, this new sum, and Mask::any, all, we probably _do_ want the reduction clause, as that might help the compiler even more. An action item here is to look at the emitted code (use `icpc -S -fsource-asm -c foo.cpp` to get annotated assembly) with and without the reduction clause.

**Comment by bartgol** [comment]
Yeah, that's the best way to check and be sure.

**Comment by jeff-cohere** [comment]
Thanks for the info, @ambrad!

**Comment by tcclevenger** [comment]
Talking with @ambrad , he suggested I take this issue (assuming no one else was planning on it).

**Comment by ambrad** [comment]
We need to handle BFB reduction of packs in a BFB build. Non-BFBness can arise like this:

F90:
```
    do k = 1,nlev  ! scalar k
       a = a + b(k)
    end do
```
C++:
```
    ||r(k_pack, a) {
       a += reduce_sum(b(k_pack)) // but this has a problem
    }
```
The value a will not be BFB-equal because reduce_sum accumulates b(k_pack), then adds it to the accumulating a. So reduce_sum actually needs to be used like this:
```
    reduce_sum(a, b(k_pack));
```
Then the impl can be something like this:
```
#ifdef BFB_BUILD
    for s..., a += b[s]
#else
    b_reduction = ... // vector impl of pack reduction
    a += b_reduction
#endif​
```

**Comment by bartgol** [comment]
Adding the homme impl of this feature as a reference. It can definitely be improved and/or simplified.

https://github.com/E3SM-Project/E3SM/blob/b7b269b3cfaca869e861fa01e6d65e201dc588a3/components/homme/src/share/cxx/ColumnOps.hpp#L474

**Comment by tcclevenger** [comment]
Great, thanks!

Does there currently exist a version of `#ifdef BFB_BUILD` in scream already?

**Comment by bartgol** [comment]
Ah, I thought we did, but I grepped and there's nothing in scream. In Ekat, I believe debug builds are always meant to have bfb enabled. However, ekat tests also access `tests/ekat_test_config.h`, which has (or doesn't, depending on config) the `EKAT_TEST_STRICT_FP` macro. You could use that to select the impl in your test.

**Comment by ambrad** [comment]
Note there's two parts to this issue: (1) the pack reduction, `packed_sum.reduce_add` in the code Luca links and (2) the wrapper that builds on the separate `parallel_reduce` wrapper from issue #32.

**Comment by bartgol** [comment]
This was completed with #37.
