### ISSUE TITLE
Add an installation (make install) target

### ISSUE THREAD

**Issue by jeff-cohere** [E3SM-Project/EKAT#28]
**Is your feature request related to a problem? Please describe.**
It would be nice if someone who uses ekat can place its libraries/headers into the proper location, given a `CMAKE_INSTALL_PREFIX`. This is pretty standard practice for libraries these days.

**Describe the solution you'd like**
I'd like to add a `make install` target that uses CMake's `install` command to put the goods where a user wants them.

**Comment by pbosler** [comment]
ekat/util headers are not installed.
