### ISSUE TITLE
Add stacktrace information to assert macros

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/EKAT#294]
Currently, our assert macros only print the file and line number where the assert was placed. For asserts placed inside common utility functions, this does not help to debug where the error generated. A stack trace, would be valuable, so that one can immediately narrow down the scope of the search.

There are a couple of options  for how to do this:
- use [boost::stacktrace](https://www.boost.org/doc/libs/1_73_0/doc/html/stacktrace/getting_started.html): this feature has been in boost for a while (I think since 1.65), so it's relatively safe to use (I would be puzzled if we could not find 1.65 if the modules or OS have boost at all).
- use backtrace from Linux [execinfo.h header](https://linux.die.net/man/3/backtrace): this is OS-specific, but the vast majority of our target machines are some flavor of Linux.

Boost would be a better solution, since it also takes care of demangling symbols. The feature could be enabled only if Boost pkg is found (and recent enough).

@jgfouca @jeff-cohere @tcclevenger thoughts?

**Comment by jeff-cohere** [comment]
I think using Boost is fine iff it's found. Certainly we don't want to bring it in as a requirement, though!

**Comment by tcclevenger** [comment]
A stacktrace would be lovely for sure.
