### ISSUE TITLE
Should EKAT have macros for defaults floating point behaviors?

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/EKAT#35]
This discussion came up during the review of #34 . The issue is the following. Some operations need to be done serially to achieve BFB. Obviously, we don't want a runtime switch, so we stick a template argument (like `bool Serialize`) in the template arguments. The question is now: should Ekat provide a default for `Serialize`, which depends on some config options? The code would look like this:

```
// With config-dependent defaults
#ifdef EKAT_BFB_DEFAULTS
template<typename T, bool Serialize = true>
#else
template<typename T, bool Serialize = false>
#endif
void foo (T& t) {
...
}

// Without config-dependent defaults (keep deducible template args last)
template<bool Serialize, typename T>
void bar (T& t) {
...
}           
```

Pros:
 - defaults make downstream code smaller; provided you configured EKAT with the correct flags, you can call `foo();` rather than `foo<true>();`;
 - people who read the code don't have to find out what the true/false tempate argument is for.

Cons:
 - if the library is installed, switching implementation (e.g., quickly checking lack of serialization yields a bug) requires reconfiguring rather than just recompiling (experienced cmake/make folks might simply hack a bunch of flags.make and link.txt files in the CMake directories, but it could be risky too, and/or be needed in a lot of cmake files).
 - if you have several template args, `Serialize` must be last (args with defaults must come after args with no defaults), so if you want/need to override the default at a specific location (perhaps for debugging) it might get complicated.

My original opinion was to not add defaults, and force customers to be explicit on what they want. If `foo` is used a lot, the app can define a wrapper that sets the `Serialize` argument depending on some _app-specific_ configuration option. However, I can see that there _is_ a value in providing the user with simpler/shorter code.

Thoughts?

**Comment by bartgol** [comment]
@jeff-cohere @jgfouca @ambrad @pbosler 

Some of you already expressed an opinion (and if you don't want to get involved into this kind of metaphysical topics that's fine). I just wanted to make sure everyone who's got interest in EKAT had a chance to share their opinion.

**Comment by ambrad** [comment]
A small point is we could make the template param default a little cleaner:
```
template<typename T, bool Serialize = EKAT_BFB_SERIALIZE>
```

**Comment by ambrad** [comment]
Another point is we can use encompassing structs to hold obvious and defaulted values (exe space, serialize) while leaving the deducible types for the contained functions.

**Comment by ambrad** [comment]
Note EKAT_MIMIC_GPU is in here, which argues in favor of EKAT being config'ed to support the testing needs of the app.

**Comment by bartgol** [comment]
> Note EKAT_MIMIC_GPU is in here, which argues in favor of EKAT being config'ed to support the testing needs of the app.

Good point.

**Comment by pbosler** [comment]
I'm in favor of the configurable defaults, whether they come via structs or default template parameters.

I understand that I may have to reconfigure/rebuild the library, or resort to a CMake hack to do so, but a rebuild is likely required for any bfb work (if not of ekat, then certainly my app).   And anything that improves readability in templated c++ is a huge win as we transition domain scientists into work with ported parameterizations.

Happy to abide by whatever the majority opinion ends up, or whatever the ekat white hats decide dictatorially (they have their reasons).
