### ISSUE TITLE
Odd behavior for reciprocal units.

### ISSUE THREAD

**Issue by pbosler** [E3SM-Project/EKAT#52]
**Describe the bug**
Odd behavior for reciprocal units, but `pow` is working correctly.

**To Reproduce**
Steps to reproduce the behavior:  in `ekat/tests/units/units.cpp`
1. Add `REQUIRE(one/mol == pow(mol,-1));`
2. Or (same result) `REQUIRE(1/mol == pow(mol,-1));`
3. run the test

> /Users/pabosle/ekat/tests/units/units.cpp:69: FAILED:
>   REQUIRE( one/mol == pow(mol,-1) )
> with expansion:
>   m s kg K A cd == mol^-1

**Comment by bartgol** [comment]
Ugh, let me check what's going on here.

**Comment by bartgol** [comment]
Uh, wow, look at what I wrote!

```
inline Units operator/(const ScalingFactor& lhs, const Units& rhs) {
  return Units(1-rhs.m_units[0],
               1-rhs.m_units[1],
               1-rhs.m_units[2],
               1-rhs.m_units[3],
               1-rhs.m_units[4],
               1-rhs.m_units[5],
               1-rhs.m_units[6],
               lhs/rhs.m_scaling);
```

So `1/(a^n) = a^(1-n)`. Math PhD fail.

**Comment by bartgol** [comment]
Also, this means that we didn't have a test for `op/`, and I'm guessing for many other operators. I will fix this.
