### ISSUE TITLE
SCREAM compilation fails with CMAKE version 3.11

### ISSUE THREAD

**Issue by singhbalwinder** [E3SM-Project/EKAT#58]
**Describe the bug**
cmake_policy CMP0074 is only available with CMAKE 3.12.0 version or higher. It might fail for machines such as compy which has a cmake version of 3.11.

**To Reproduce**
Compile Scream on Compy machine (or any any machine with older CMAKE version) 

**Expected behavior**
Model should compile with versions older than CMAKE 3.12.0
The following code if added to `CMakeLists.txt` fixes this issue:
```
IF(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.12.0")
    cmake_policy(SET CMP0074 NEW)
ENDIF(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.12.0")
```

**Comment by bartgol** [comment]
@singhbalwinder could you please put your fix in a quick PR?

**Comment by singhbalwinder** [comment]
Sure. I will issue a PR soon.
