### ISSUE TITLE
Ability to call `scream_kerror_msg` with a string variable

### ISSUE THREAD

**Issue by singhbalwinder** [E3SM-Project/EKAT#6]
I am trying to do the following using `scream_kerror_msg` function :
```
const char* errstr = "some error message";
scream_kerror_msg(errstr);
```
and getting the following error:
```
scream/components/scream/src/physics/share/physics_saturation_impl.hpp(21): error: expected a ")"
          detected during:
            instantiation of "scream::physics::Functions<ScalarT, DeviceT>::Spack scream::physics::Functions<ScalarT, DeviceT>::qv_sat(const screa\
m::physics::Functions<ScalarT, DeviceT>::Spack &, const scream::physics::Functions<ScalarT, DeviceT>::Spack &, __nv_bool, const scream::physics::F\
unctions<ScalarT, DeviceT>::Smask &, scream::physics::Functions<ScalarT, DeviceT>::SaturationFcn) [with ScalarT=scream::Real, DeviceT=scream::Defa\
ultDevice]"
```
Please note that the following code works:
```
scream_kerror_msg("Some error message");
```
Therefore, `scream_kerror_msg` is not able to take a variable as an argument.

**Is your feature request related to a problem? Please describe.**
A : Yes, I am trying to build an error message dynamically but this function requires an explicit string.

**Describe the solution you'd like**
A Ability to call this function with a variable argument

**Comment by jgfouca** [comment]
@bartgol , I wrote our assertion macros, so I can take this one.
