### ISSUE TITLE
Update kokkos submodule to mirror e3sm

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/EKAT#67]
PR E3SM-Project/E3SM#3893 is updating the kokkos submodule, to fix an error related to kokkos use of the dl library on cray systems. The error is also visible in SCREAM (see E3SM-Project/scream#679).

We should update the kokkos submodule in ekat to point to the libdl-fix branch on the E3SM-Project/kokkos repo.

@jeff-cohere @jgfouca any reason why ekat should keep a different version than e3sm? I mean, _if_ EKAT becomes the main provider of kokkos for e3sm, it must provide a version that satisfy e3sm needs, after all.

**Comment by jeff-cohere** [comment]
I don't see any reason for EKAT to maintain a different version of Kokkos from E3SM, absent any specific technical reason. It's easier if they're the same--fewer details to remember. 

Another version of the same question is: should E3SM projects rely on more than one version of Kokkos? (Doesn't sound like fun, does it? 😬)

**Comment by bartgol** [comment]
Was done in #68
